[global]
showWarningOnDirectExecution = true

[logger]
level = "debug"

[runner]
magicEnabled = true

[server]
folderWatchBlacklist = ['']
headless = true
liveSave = false
runOnSave = false
port = 80
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = true
serverPort = 80

[theme]
primaryColor = "#FFB800" # Royal Gold
backgroundColor = "#0C0B10" # Rich Deep Charcoal Black
secondaryBackgroundColor = "#1E1E26" # Translucent Dark Charcoal
textColor = "#F3F4F6" # Ice White Text
font = "sans serif"
